### ISSUE TITLE
Support for IEG55

### ISSUE THREAD

**Issue by gcbeneke** [ipa320/weiss_gripper_ieg76#2]
Dear reader,

Does this software support the IEG55-020 as well? I have followed your instructions but I can't get my IEG55-020 to work. I get the following error:

import transitions
ImportError: No module named transitions
[weiss_gripper_ieg76_driver-1] process has died [pid 15714, exit code 1, cmd /home/gijs/irb_ws/src/weiss_gripper_ieg76/src/driver.py __name:=weiss_gripper_ieg76_driver __log:=/home/gijs/.ros/log/98bca95a-ef18-11e8-aef7-3497f672e4fe/weiss_gripper_ieg76_driver-1.log].
log file: /home/gijs/.ros/log/98bca95a-ef18-11e8-aef7-3497f672e4fe/weiss_gripper_ieg76_driver-1*.log

Is this error due to the different gripper module I am using? Or am I missing the transitions module?

Kind regards,

Gijs Beneken Kolmer

**Comment by lorenz-halt** [comment]
Hi,
we use it with an ieg55.

You need to install python-transition, it's a dependency.

you may use rosdep:
rosdep install weiss_gripper_ieg76

**Comment by gcbeneke** [comment]
Thank you, that worked.
